source 'https://rubygems.org'

gem 'chefspec'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'chef', '~> 11.0'
gem 'foodcritic', '~> 3.0.0'
gem 'daptiv-foodcritic-rules'
gem 'tailor'
gem 'rake'
gem 'berkshelf', '~> 2.0.14'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '~> 0.0.14'
