source 'http://artrepo.daptiv.com:8081/artifactory/api/gems/rubygems-virtual/'

gem 'chefspec', '~> 4.1.1'
gem 'rspec', '~> 3.1.0'
gem 'rspec-core', '~> 3.1.7'
gem 'rspec-expectations', '~> 3.1.2'
gem 'rspec-mocks', '~> 3.1.3'
gem 'chef', '~> 11.14'
gem 'foodcritic', '~> 3.0.0'
gem 'daptiv-foodcritic-rules', '~> 0.0.2'
gem 'log_switch', '~> 0.4.0'
gem 'tailor'
gem 'rake'
gem 'berkshelf', '~> 3.2.3'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '~> 0.0.13'