name             'visualstudio'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
source_url       'https://github.com/sous-chefs/visualstudio'
issues_url       'https://github.com/sous-chefs/visualstudio/issues'
chef_version     '>= 13.0'
license          'Apache-2.0'
description      'Installs/Configures Visual Studio'
version          '3.0.2'
supports         'windows'
depends          'windows'
depends          'seven_zip'
