name             'visualstudio'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/visualstudio'
issues_url       'https://github.com/windowschefcookbooks/visualstudio/issues'
chef_version     '>= 13.0'
license          'Apache-2.0'
description      'Installs/Configures Visual Studio'
version          '2.0.2'
supports         'windows'
depends          'windows'
depends          'seven_zip'
